export const ALLUNIVERSE = [
    { value: "All", name: "All universes" },
    { value: "Marvel Comics", name: "Marvel" },
    { value: "DC Comics", name: "DC" },
    { value: "Shueisha", name: "Shueisha" },
    { value: "Dark Horse Comics", name: "Dark Horse Comics" },
    { value: "George Lucas", name: "George Lucas" },
    { value: "IDW Publishing", name: "IDW Publishing" },
    { value: "Image Comics", name: "Image Comics" },
    { value: "Warner Bros", name: "Warner Bros" },
    // { value: "Angel", name: "Angel" },
    { value: "NBC - Heroes", name: "NBC - Heroes" },
    { value: "Tempest", name: "Tempest" },
    { value: "SyFy", name: "SyFy" },
    { value: "ABC Studios", name: "ABC Studios" },
    { value: "Icon Comics", name: "Icon Comics" },
    { value: "Universal Studios", name: "Universal Studios" },
    { value: "Gemini V", name: "Gemini V" },
    { value: "Star Trek", name: "Star Trek" },
    // { value: "Goliath", name: "Goliath" },
    // { value: "Deadpool", name: "Deadpool" },
    { value: "Wildstorm", name: "Wildstorm" },
    { value: "South Park", name: "South Park" },
    { value: "Sony Pictures", name: "Sony Pictures" },
    { value: "Vindicator II", name: "Vindicator II" },
    { value: "Image Comics", name: "Image Comics" },
    { value: "Titan Books", name: "Titan Books" },
    { value: "J. K. Rowling", name: "J. K. Rowling" },
    { value: "Microsoft", name: "Microsoft" },
    // { value: "She-Thing", name: "She-Thing" },
    { value: "Rebellion", name: "Rebellion" },
    { value: "J. R. R. Tolkien", name: "J. R. R. Tolkien" },
    { value: "Carolco Pictures", name: "Carolco Pictures" },
    { value: "ARK corporation", name: "ARK corporation" },
    { value: "Paramount Pictures", name: "Paramount Pictures" },
    { value: "-", name: "-" },
    // { value: null, name: "null" },
    { value: "Real people", name: "Real people" },
  
    //
  ];